# Generated by Django 5.0.3 on 2024-03-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdzapp', '0002_alter_book_parts_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='parts',
        ),
        migrations.AddField(
            model_name='book',
            name='parts',
            field=models.ManyToManyField(to='gdzapp.parts'),
        ),
    ]
